before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: FwdiudlPMP9WKZVm9f0t6SmQR8khwjqQYMemDDPeRDa7c/vBxqCzo5TDtRYphZ+2Jl8/2r5oBXQIh7TxLVAGJT0H6/kgx4zrJkUO/B2Ar3en7mKexd2lPNdy1pk0f0cmdwcdt7a6QhGdQiES/z+aulPrW0d7gnveTpg/SMgahEvNLhv2I2WybszSV79ApezeC0LgGfdWro9fVyJkesWL1KQY+leLx9VClwp3KY13dYXy0INHUCVUgkTfu1MMrLZTDbFzdlUjTyAs9wuWW5ZEQAJ8Dbo2zqoV7/ceD7coASJydD3yxRyAZYZCIWy8RpjHEPU1upfCfjh0amGxN9QmEdvfHd9tUb5b6cI3Kb1/lzTyHdAc/ujClSPNNbdGVv+E3sCbXY6tumqjQ68n2eynHt6s01tpD9odNwXvp0TkbYBUfsibbTKPB1qxm2Q8059QYq9ZpATuBfG0jzvhVeC4M/YRT/HP4z388ylkLaGL1Sca9uVtxqinTNwlz9Bz0zThqV10fiVLKjtvak7YKAFKhGTcPSw4yveLiYnvaBleCxoaqPp6+ckal3Y/hDbU+/Vgf0kqKU7G+8Hoj0Lgzz9NqGvIAHWIqWoyg39iAwwmkAIwVEbEUVYchdX0/k1o0B5oOWIto/URVdLz4zOHDbrJCdtFHM6RB40Z0vdNYKN6Jcc= # CRYPTO_AES_KEY
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
